experiment:
  name: "resnet18"
  seed: 42
  device: "cuda"

model:
  name: "resnet18"
  in_channels: 3
  num_classes: 10

dataset:
  name: "EuroSAT"
  image_size: 224
  batch_size: 128

training:
  epochs: 40
  optimizer:
    name: "adam"
    lr: 0.001
    weight_decay: 0.0001
